version: "3"

services:
  maven-npm:
    image: dimajix/maven-npm:latest
    build:
      context:  .
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}

